# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: [push]

env:
  node-version: "16.17.1"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
        cache: 'npm'
    - uses: actions/cache@v3
      id: node_modules_cache_id
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
    - run: echo '${{ toJSON(steps.node_modules_cache_id.outputs) }}'
    - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
      run: npm ci
    - run: npm ls --depth=0
  typecheck:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
        cache: 'npm'
    - uses: actions/cache@v3
      id: node_modules_cache_id
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
    - run: npm run typecheck -w @example/webpack
    - run: npm run typecheck -w @example/next 
